openapi: 3.0.0
info:
  title: webservice_js
  version: 1.0.0
servers:
  - url: https://books-server-eight.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: categories
  - name: books
paths:
  /registration:
    post:
      tags:
        - auth
      summary: regis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                fullname: Uca Ganteng
                email: ucaganteng@gmail.com
                username: ucaganteng
                password: '1234'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: ucaganteng
                password: '1234'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /assign-role/2:
    put:
      tags:
        - auth
      summary: role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                admin: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /insert-categories:
    post:
      tags:
        - categories
      summary: insert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Psychological Thriller
                description: >-
                  Thriller psikologis adalah genre yang menggabungkan genre
                  thriller dan fiksi psikologis
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /categories:
    get:
      tags:
        - categories
      summary: get all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-categories/{id}:
    get:
      tags:
        - categories
      summary: get by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-categories/{id}:
    delete:
      tags:
        - categories
      summary: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 3
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-categories/{id}:
    put:
      tags:
        - categories
      summary: update
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
        - in: body
          description: Updated category information
          required: true
          schema:
            type: object
            example:
              name: Sci-Fi
              description: >-
                fiction that primarily deals with the impact of actual or imagined science on society or individuals
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /insert-books:
    post:
      tags:
        - books
      summary: insert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: test
                author: test
                year: 2002
                cover_image: test.jpg
                categories_id: 2
                summary: test
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books:
    get:
      tags:
        - books
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-books/{id}:
    get:
      tags:
        - books
      summary: get by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-books/{id}:
    put:
      tags:
        - books
      summary: put
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
        - in: body
          description: Updated book information
          required: true
          schema:
            type: object
            example:
              title: testing
              author: test
              year: 2006
              cover_image: test.jpg
              categories_id: 2
              summary: test
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-books/{id}:
    delete:
      tags:
        - books
      summary: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
